version: '2.4'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    environment:
      - VERSION=docker
      - TZ=Europe/Paris
      - PLEX_CLAIM=${CLAIM}
      - ADVERTISE_IP=${HTTPS_NAME}
    volumes:
      - plexConfig:/config
      - plexNfsMount:/data/videos
    ports:
      - 32400:32400
                        
volumes:
  plexConfig:
  plexNfsMount:
    driver_opts:
      type: nfs
      o: ${NFS}
      device: ':/volume1/video'