version: "1"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 8004:80/tcp
      - 443:443/tcp
    volumes:
      - data-work:/opt/adguardhome/work
      - data-conf:/opt/adguardhome/conf
    restart: unless-stopped

volumes:
  data-work:
  data-conf:
