version: '4.0'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io:0.48.04
      container_name: changedetection
      hostname: changedetection
      volumes:
        - changedetection-data:/datastore
      ports:
        - 5000:5000
      restart: unless-stopped
      
volumes:
  changedetection-data:

