version: '1.0'
services:
    changedetection:
      image: lscr.io/linuxserver/changedetection.io:latest
      container_name: changedetection
      hostname: changedetection
      volumes:
        - changedetection-data:/datastore
      ports:
        - 5000:5000
      restart: unless-stopped
      
volumes:
  changedetection-data:

