version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - TZ=Europe/Paris
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - config:/config
    ports:
      - 8443:8443 # Unifi web admin port
      - 3478:3478/udp # Unifi STUN port
      - 10001:10001/udp # Required for AP discovery
      - 8080:8080 # Required for device communication
      - 1900:1900/udp #optional, Required for Make controller discoverable on L2 network option
      - 8843:8843 #optional, Unifi guest portal HTTPS redirect port
      - 8880:8880 #optional, Unifi guest portal HTTP redirect port
      - 6789:6789 #optional, For mobile throughput test
      - 5514:5514/udp #optional, Remote syslog port
    restart: unless-stopped
    
volumes:
  config:
