services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - data-kuma:/app/data
    ports:
      - 3022:3001

volumes:
  data-kuma:
