version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    env_file:
      - .env
    environment:
      TZ: 'Europe/Paris'
      SERVER_ADMIN: ${ADMIN_MAIL}
      HTTP_SERVER_NAME: ${HTTP_NAME}
      HTTPS_SERVER_NAME: ${HTTPS_NAME}
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - linkstack_data:/htdocs
    ports:
      - 8190:443
    restart: unless-stopped

volumes:
  linkstack_data2:

